version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "khaya-backend"
s3_prefix = "khaya-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FrontendUrl=https://khaya.co.za"
confirm_changeset = false
resolve_s3 = true

[default.build]
[default.build.parameters]
cached = true
parallel = true
